Development/practice3/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root "items#index"

  resources :items do
    member do
      get :toggle
      get :add
    end
  end

  resources :orders
  resources :user_items
end

Development/practice3/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

Development/practice3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Development/practice3/app/models/category.rb
class Category < ApplicationRecord
  def self.generate_categories
    %w(
      식품/생활
      가전/디지털
      패션/뷰티
      여행/레저
    ).each_with_index do |category_title, index|
      Category.create(title: category_title, position: index)
    end
  end
end

Development/practice3/app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category, optional: true

  mount_uploader :image, ImageUploader

  has_many :line_items, dependent: :nullify
  has_many :line_items, dependent: :destroy

  def self.generate_items
    %w(
      파리
      로마
      뉴욕
      런던
      다낭
      자카르타
      베이징
      도쿄
    ).each do |title|
      category = Category.fourth
      Item.create(title: title, price: 2000000, category: category, image: Item.first.image, user: User.first)
    end
  end
end

Development/practice3/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :order, optional: true
  belongs_to :item, optional: true

  after_save :set_order_total

  def set_order_total
    order.update(total: order.line_items.sum("amount * price"))
  end
end

Development/practice3/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  enum status: [:cart, :paid, :canceled]

  has_many :line_items, dependent: :destroy
end

Development/practice3/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_items, dependent: :destroy
  has_many :items, dependent: :nullify

  has_many :orders

  def has_item? item
    user_items.where(item: item).present?
  end
end

Development/practice3/app/models/user_item.rb
class UserItem < ApplicationRecord
  belongs_to :user
  belongs_to :item
  
end

Development/practice3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def get_cart
    current_user.orders.cart.first_or_create
  end
end

Development/practice3/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_object, only: [:show, :toggle, :add, :edit, :update, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]

  def index
    if params[:type] == "selling"
      redirect_to root_path
      @items = current_user.items
    else
      @items = Item.all
      if params[:category_id].present?
        @category = Category.find(params[:category_id])
        @items = @items.where(category_id: params[:category_id])
      end
      # @items = params[:order].blank? ?  @item.order(created_at: :desc) : @items.order(params[:order])
      @items = @items.ransack(title_or_description_cont: params[:q]).result(distinct: true) if params[:q].present?
    end
  end

  def show
  end

  def add
    @order = get_cart
    line_item = @order.line_items.where(item: @item).first_or_create(price: @item.price)
    line_item.increment!(:amount)
    line_item.set_order_total
    redirect_to new_order_path
  end

  def toggle
    if user_item = current_user.user_items.where(item: @item).first
      user_item.destroy
    else
      current_user.user_items.where(item: @item).create
    end
    redirect_to @item
  end

  def edit

  end

  def update
    @item.update(item_params)
    redirect_to item_path
  end

  def destroy
    @item.destroy
    redirect_back fallback_location: root_path
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    @item.update(user: current_user)
    redirect_to items_path(type: :selling)
  end

  private
    def load_object
      @item = Item.find params[:id]
    end

    def item_params
      params.require(:item).permit(:user_id, :title, :price, :description, :iamge, :category_id)
    end

    def check_owner
      redirect_to root_path unless @item.user == current_user
    end
end

Development/practice3/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_object, only: [:update, :show, :edit]
  before_action :check_owner, only: [:edit, :show, :update]

  def index
    @orders = current_user.orders.order(:paid_at)
  end

  def edit

  end

  def new
    @order = get_cart
  end

  def update
    @order.paid!
    @order.update(paid_at: Time.now)
    redirect_to @order
  end

  private
    def load_object
      @order = Order.find params[:id]
    end

    def check_owner
      redirect_to root_path unless @order.user == current_user
    end
end

Development/practice3/app/controllers/user_items_controller.rb
class UserItemsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_items = current_user.user_items
  end
end

Development/practice3/app/helpers/application_helper.rb
module ApplicationHelper
end

Development/practice3/app/helpers/items_helper.rb
module ItemsHelper
end

Development/practice3/app/helpers/orders_helper.rb
module OrdersHelper
end

Development/practice3/app/helpers/user_items_helper.rb
module UserItemsHelper
end

Development/practice3/app/views/items/_form.html.erb
<div class="container my-5">
  <div class="row">
    <div class="card col-md-5 offset-md-3 p-5">
      <%= form_for @item do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price %>
          <%= f.text_field :price, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :category_id %>
          <%= f.select :category_id, options_for_select(Category.order(:position).map{|category| [category.title, category.id]}), {}, class: "form-control" %>
        </div>
        <%= f.submit "상품 등록", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

Development/practice3/app/views/items/edit.html.erb
<%= render "form" %>

Development/practice3/app/views/items/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12 mb-3">
      <% if params[:type] == "selling" %>
        <h2>나의상품</h2>
      <% elsif @category %>
        <h2><%= @category.title %></h2>
      <% end %>
      <hr>
      <%= form_tag request.parameters, method: :get do%>
        <div class="form-inline">
          <%= text_field_tag :q, params[:q], class: "form-control mr-1" %>
          <%= submit_tag "검색", class: "btn btn-primary mr-1" %>
          <div class="float-right">
            <div class="button-group">
              <%= link_to "가격순", request.parameters.merge(order: :price), class: "btn btn-secondary" %>
              <%= link_to "등록순", request.parameters.merge(order: nil), class: "btn btn-light" %>
            </div>
          </div>
        </div>
      <% end %>
      <%= link_to "상품 등록", new_item_path, class: "btn btn-primary float-right" %>

    </div>
  </div>

  <div class="row">
    <% @items.each do |item| %>
    <div class="col-md-3 mb-3">
      <div class="card">
        <img src="<%= item.image.url(:thumb) if item.image? %>" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= item.title %></h5>
          <div class="card-subtitle">
            판매자: <%= item.user&.email %>
          </div>
          <p class="card-text"><%= item.description %></p>
          <p class="text-muted"><%= number_with_delimiter item.price %></p>
        </div>
        <div class="card-footer">
          <%= link_to "자세히보기", item, class: "btn btn-primary" %>
          <% if item.user == current_user %>
            <%= link_to "수정", edit_item_path(item), class: "btn btn-danger" %>
            <%= link_to "삭제", item, mothod: :delete, data: {confirm: "정말 삭제하겠습니까?"}, class: "btn btn-secondary" %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

Development/practice3/app/views/items/new.html.erb
<div class="container my-5">
  <div class="row">
    <div class="card col-md-5 offset-md-3 p-5">
      <%= form_for @item do |f| %>
        <div class="form-group">
          <%= f.label :user_id %>
          <%= f.select :user_id, options_for_select(User.order(:id).map{|user| [user.id]}), {}, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :price %>
          <%= f.text_field :price, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :category_id %>
          <%= f.select :category_id, options_for_select(Category.order(:position).map{|category| [category.title, category.id]}), {}, class: "form-control" %>
        </div>
        <%= f.submit "상품 등록", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

Development/practice3/app/views/items/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @item.image.url, class: "img-thumbnail img-fluid" %>
    </div>
    <div class="col-md-8">
      <h4><%= @item.title %></h4>
      <p><%= number_with_delimiter @item.price %>원</p>
      <p><%= @item.description %></p>

      <%= link_to current_user.has_item?(@item) ? "찜취소하기" : "찜하기", toggle_item_path(@item), class: "btn btn-secondary" %>
      <%= link_to "장바구니 담기", add_item_path(@item), class: "btn btn-primary" %>
    </div>
  </div>
</div>

Development/practice3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

Development/practice3/app/views/orders/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col">
      <div class="card p-5">
        <h3>주문 정보 입력</h3>
        <hr>
        <%= form_for @order do |f| %>
          <div class="form-group">
            <%= f.label :zipcode %>
            <%= f.text_field :zipcode, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :address1 %>
            <%= f.text_field :address1, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :address2 %>
            <%= f.text_field :address2, class: "form-control" %>
          </div>
        <%= f.submit "결제하기", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

Development/practice3/app/views/orders/index.html.erb
<div class="container my-4">
  <div class="row">
    <div class="col">
      <% @orders.each do |order| %>
        <div class="card p-3 mb-3">
          <% order.line_items.each do |line_item| %>
            <% if item = line_item.item %>
              <%= line_item.item.title %> (<%= number_with_delimiter (line_item.price) %> 원 * <%= line_item.price %> 개)
            <% else %>
              삭제된 상품 입니다
            <% end %>
          <% end %>
          <hr>
          <%= number_with_delimiter order.total %> 원
        </div>
      <% end %>
    </div>
  </div>
</div>

Development/practice3/app/views/orders/new.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-12">

          <% if @order.line_items.blank? %>
            <div class="card p-3 text-center">
              장바구니가 비었습니다
            </div>
          <% end %>

          <% @order.line_items.each do |line_item| %>
          <div class="card p-3 mb-4">
            <%= line_item.item.title %>
            <%= line_item.amount %> 개
          </div>
          <% end %>
          <p>
            합계 : <%= number_with_delimiter @order.total %>
          </p>
        <%= link_to "주문하기", add_item_path(@order), class: "btn btn-primary" %>

    </div>
  </div>
</div>

Development/practice3/app/views/orders/show.html.erb
<!-- 주문 정보를 입력하기 위한 페이지 -->
<div class="container my-4">
  <div class="row">
    <div class="col">
      <div class="card p-3">
        <%= number_with_delimiter @order.total %>
      </div>
    </div>
  </div>
</div>

Development/practice3/app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container">
    <a class="navbar-brand" href="/">Market</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <% Category.order(:position).each do |category| %>
          <li class="nav-item">
            <a class="nav-link <%= params[:category_id].to_i == category.id ? "active" : "" %>" href="<%= items_path(category_id: category.id) %>"><%= category.title %></a>
          </li>
        <% end %>

        <% if current_user%>
        <li class="nav-item">
          <a class="nav-link" href="<%= edit_user_registration_path %>">회원 정보 수정</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_order_path %>">장바구니</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= items_path(type: :selling) %>">나의 상품</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= user_items_path() %>">찜한 상품</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= orders_path %>">나의 주문</a>
        </li>
        <li class="nav-item">
          <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>

        <% else %>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_session_path %>">로그인</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= new_user_registration_path %>">회원가입</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

Development/practice3/app/views/user_items/index.html.erb
<div class="container my-5">

  <div class="row">
    <div class="col-12 mb-2">
      <% if params[:type] == "selling" %>
        <h2>나의 상품</h2>
      <% elsif @category %>
        <h2><%= @category.title %></h2>
      <% end %>
    </div>
    <% @user_items.each do |user_item| %>
    <% if item = user_item.item %>
      <div class="col-md-3 mb-3">
        <div class="card">
          <img src="<%= item.image.url(:thumb) if item.image? %>" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title"><%= item.title %></h5>
            <div class="card-subtitle">
              판매자: <%= item.user&.email %>
            </div>
            <p class="card-text"><%= item.description %></p>
            <%= link_to "자세히보기", item, class: "btn btn-primary" %>
            <% if item.user == current_user %>
              <%= link_to "수정", edit_item_path(item), class: "btn btn-danger" %>
              <%= link_to "삭제", item, mothod: :delete, data: {confirm: "정말 삭제하겠습니까?"}, class: "btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>